CREATE DATABASE IF NOT EXISTS forumSite;

USE forumSite;

CREATE TABLE Sous_section(
nomSection VARCHAR(50),
nomSsSection VARCHAR(100),
description TEXT,
PRIMARY KEY (nomSection, nomSsSection));

CREATE TABLE Sujet(
idSuj SMALLINT UNSIGNED AUTO_INCREMENT,
nomSection VARCHAR(50),
nomSsSection VARCHAR(100),
nomSujet VARCHAR(200),
PRIMARY KEY (idSuj));

CREATE TABLE Post(
idSuj SMALLINT UNSIGNED,
noPost SMALLINT UNSIGNED AUTO_INCREMENT,
datePost DATE,
textePost LONGTEXT,
pseudo VARCHAR(200),
PRIMARY KEY (noPost, idSuj));

CREATE TABLE Personne(
pseudo VARCHAR(50),
avatar MEDIUMBLOB,
anniversaire DATE,
dateInscrip DATE,
dateDerConnex DATE,
PRIMARY KEY (pseudo));

CREATE TABLE SujetMP(
noSujetMP SMALLINT UNSIGNED AUTO_INCREMENT,
nomSujet VARCHAR(150),
dateSujMP DATE,
PRIMARY KEY (noSujetMP));

CREATE TABLE MP(
noSujetMP SMALLINT UNSIGNED,
noMP SMALLINT UNSIGNED AUTO_INCREMENT,
texte LONGTEXT,
pseudo VARCHAR(50),
PRIMARY KEY (noMP, noSujetMP));

CREATE TABLE News(
noNews SMALLINT UNSIGNED AUTO_INCREMENT,
texteNews LONGTEXT,
titre VARCHAR(255),
jour DATE,
PRIMARY KEY (noNews));

CREATE TABLE Commentaire(
noNews SMALLINT UNSIGNED,
noCom SMALLINT UNSIGNED AUTO_INCREMENT,
pseudo VARCHAR(50),
texteCom TEXT,
dateCom DATE,
PRIMARY KEY (noCom, noNews));

CREATE TABLE RecoitMP(
noSujetMP SMALLINT UNSIGNED,
pseudo VARCHAR(50),
PRIMARY KEY (noSujetMP, pseudo));

CREATE TABLE Appartient(
pseudo VARCHAR(50),
nomGroupe VARCHAR(50),
logo MEDIUMBLOB,
PRIMARY KEY (pseudo, nomGroupe));

CREATE TABLE Concoit(
noNews SMALLINT UNSIGNED,
pseudo VARCHAR(50),
nomSource VARCHAR(150),
ref TINYTEXT,
PRIMARY KEY (noNews, nomSource));


